# Basics of NumPy

NumPy - Numerical Python

Advantages of Numpy Arrays:
1. Allows several mathematical operations
2. Faster operations

In [1]:
import numpy as np
from numpy.ma.core import indices

### List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000000)]

start_time = process_time()

python_list = [i+5 for i in python_list]    #adding 5 in all the values of i one by one

end_time = process_time()

print(end_time - start_time)

0.421875


Time taken by an numpy array

In [4]:
np_array = np.array([i for i in range(10000000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.015625


* time taken by list = 0.546875ms and
* time taken by numpy array = 0.051625ms

Hence it can be clearly seen that numpy array takes less time for the execution. This is one of the major advantage to use numpy arrays over the lists.

### Numpy Arrays

In [5]:
# List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
# arrays
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)          # ndarray means the n-dimensional array

[1 2 3 4 5]


numpy.ndarray

1-D Array

In [7]:
oned_array = np.array([10,20,30,40,50])
print(oned_array)
oned_array.shape

[10 20 30 40 50]


(5,)

* Shape method is used to show the no of rows and the no of columns in an array
* ndim method is used to print the no of dimensions of the array

2-D Array

In [8]:
twod_array = np.array([(10, 20, 30, 40, 50), (23, 43, 32, 54, 65)])
print(twod_array)
twod_array.shape

# twod_array.ndim -> 2 (it means the no of dimensions in the array)

[[10 20 30 40 50]
 [23 43 32 54 65]]


(2, 5)

* There are 2 rows and the 5 columns in the twod_array

Also we can create an array with the floating point values

In [9]:
c = np.array([(10,20,30,40,50), (23, 43, 32, 54, 65)], dtype=float)
print(c)
type(c)

[[10. 20. 30. 40. 50.]
 [23. 43. 32. 54. 65.]]


numpy.ndarray

Initial placeholders in numpy arrays

In [10]:
# create a numpy arrays of zeros
x = np.zeros((4, 5))        #it means that all the values are zeros of the matrix in which 4 rows and 5 columns are there.
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# create an numpy array of ones
y = np.ones((6, 2))
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
# create an numpy array of a particular value
z = np.full((3, 4), 7)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [13]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


1. we don't need to specify the no of rows and cols because identity matrix have equal values of rows and cols. Hence we only need to specify the size of the matrix, in this case size is 4. Therefore, it create a 4x4 matrix in which diagonal elements are 1.
2. eye() function is used to create the identity matrix..

In [14]:
# create a numpy array with the random values
b = np.random.random((4, 5))
print(b)

[[0.68301935 0.12778808 0.35148915 0.45284389 0.75818356]
 [0.99279993 0.88986564 0.01168817 0.77251679 0.71366597]
 [0.91422054 0.29365173 0.52550587 0.55324383 0.85693392]
 [0.09448708 0.02161394 0.51269028 0.07766995 0.91792237]]


In [15]:
# random integer values array within a specific range
c = np.random.randint(10, 100, (3, 5))
print(c)

[[79 33 58 12 51]
 [64 59 83 42 26]
 [38 22 47 23 55]]


it means that the array size is 3x5 in which elements are random integers values from 10 to 100

flatten() converts all the elements of the array in one row.
it returns the copy of the original array

ravel() -> returns view, instead of copy

In [16]:
c = np.random.randint(10, 100, (3, 5))
flattened_c = c.flatten()
print(flattened_c)

raveled_c = c.ravel()
print(raveled_c)

[58 25 67 80 66 56 11 86 88 38 27 61 62 32 59]
[58 25 67 80 66 56 11 86 88 38 27 61 62 32 59]


In [17]:
# array of evenly spaced values ---> specifying the number of values required
#ex-1
d = np.linspace(10, 30, 5)
print(d)

# ex-2
e = np.linspace(10, 30, 6)
print(e)

# ex-3
f = np.linspace(1, 3, 4)
print(f)

[10. 15. 20. 25. 30.]
[10. 14. 18. 22. 26. 30.]
[1.         1.66666667 2.33333333 3.        ]


evenly spaced means the difference btw two elements are same

(in ex-2 it concludes that we require total 6 values with same difference and they lies btw from 10 to 30 and same for other examples)

In [18]:
# array of evenly spaced values ---> specifying the step
# ex-1
g = np.arange(10, 20, 4)
print(g)

# ex-2
h = np.arange(20, 100, 4)
print(h)

[10 14 18]
[20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92 96]


1. it means that no of values are not required here.
2. here we required the no of steps.
3. it means that the elements of the matrix should lies btw 10 to 20 but the step should be 4.
4. it means that the first element strat with 10 then the next is after 4 steps i.e. 14 and then 18

In [19]:
# convert a list into an numpy array
print("converting a list into an numpy array")
list2 = [(10, 20, 30, 20, 40, 40), (10, 20, 30, 20, 40, 40)]
print(list2)

np_array = np.asarray(list2)
print(np_array)
type(np_array)


# converting a tuple into an array
print("converting a tuple into a numpy array")
list3 = ((1, 3, 5, 6), (7, 8, 9, 4))
print(list3)

npp_array = np.asarray(list3)
print(npp_array)
type(npp_array)

converting a list into an numpy array
[(10, 20, 30, 20, 40, 40), (10, 20, 30, 20, 40, 40)]
[[10 20 30 20 40 40]
 [10 20 30 20 40 40]]
converting a tuple into a numpy array
((1, 3, 5, 6), (7, 8, 9, 4))
[[1 3 5 6]
 [7 8 9 4]]


numpy.ndarray

### Analysing a numpy array

In [20]:
c = np.random.randint(10, 100, (5, 5))
print(c)

[[25 12 59 65 13]
 [59 67 75 51 28]
 [37 42 18 99 54]
 [38 63 41 72 64]
 [94 91 40 49 96]]


In [21]:
# array dimension---> rows and columns
print(c.shape)

(5, 5)


In [22]:
# number of dimensions----> it means there are only rows and columns in the array so it has only 2D array
print(c.ndim)

2


In [23]:
# number of elements in the array
print(c.size)

25


In [24]:
# check the datatype of values in the array
print(c.dtype)

int32


### Mathematical operations on a numpy array

* Addition and concatenation

In [25]:
# concatenation of lists
list1 = [5, 3, 2, 4, 6]
list2 = [52, 31, 24, 43, 64]
print("the lists are: ",list1, list2)
print("concatenated list is: ",list1 + list2)



# numpy arrays creation
np_array1 = np.random.randint(0, 10, (3, 3))
np_array2 = np.random.randint(10, 20, (3, 3))
print("numpy arrays are: ")
print(np_array1)
print(np_array2)

# concatenation of arrays
print("concatenated numpy arrays are: ")
print(np.concatenate((np_array1, np_array2)))

# addition of two numpy arrays
print("addition of numpy arrays are: ")
print(np_array1 + np_array2)

# subtraction of np arrays
print("subtraction of numpy arrays are: ")
print(np_array1 - np_array2)

# product of np arrays
print("product of numpy arrays are: ")
print(np_array1 * np_array2)

# division of np arrays
print("division of numpy arrays are: ")
print(np_array1 / np_array2)

the lists are:  [5, 3, 2, 4, 6] [52, 31, 24, 43, 64]
concatenated list is:  [5, 3, 2, 4, 6, 52, 31, 24, 43, 64]
numpy arrays are: 
[[1 6 4]
 [5 8 8]
 [8 6 5]]
[[18 18 19]
 [19 10 19]
 [18 16 15]]
concatenated numpy arrays are: 
[[ 1  6  4]
 [ 5  8  8]
 [ 8  6  5]
 [18 18 19]
 [19 10 19]
 [18 16 15]]
addition of numpy arrays are: 
[[19 24 23]
 [24 18 27]
 [26 22 20]]
subtraction of numpy arrays are: 
[[-17 -12 -15]
 [-14  -2 -11]
 [-10 -10 -10]]
product of numpy arrays are: 
[[ 18 108  76]
 [ 95  80 152]
 [144  96  75]]
division of numpy arrays are: 
[[0.05555556 0.33333333 0.21052632]
 [0.26315789 0.8        0.42105263]
 [0.44444444 0.375      0.33333333]]


In [26]:
# another method to perform the same operations on numpy arrays: (+ - * /)
# numpy arrays creation
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))
print("numpy arrays are: ")
print(a)
print(b)

# addition of two numpy arrays
print("addition of numpy arrays are: ")
print(np.add(a, b))

# subtraction of np arrays
print("subtraction of numpy arrays are: ")
print(np.subtract(a, b))

# product of np arrays
print("product of numpy arrays are: ")
print(np.multiply(a, b))

# division of np arrays
print("division of numpy arrays are: ")
print(np.divide(a, b))

numpy arrays are: 
[[5 4 3]
 [2 4 5]
 [5 5 0]]
[[11 15 18]
 [11 14 19]
 [11 10 14]]
addition of numpy arrays are: 
[[16 19 21]
 [13 18 24]
 [16 15 14]]
subtraction of numpy arrays are: 
[[ -6 -11 -15]
 [ -9 -10 -14]
 [ -6  -5 -14]]
product of numpy arrays are: 
[[55 60 54]
 [22 56 95]
 [55 50  0]]
division of numpy arrays are: 
[[0.45454545 0.26666667 0.16666667]
 [0.18181818 0.28571429 0.26315789]
 [0.45454545 0.5        0.        ]]


* Indexing & Slicing

In [27]:
# 1-D array
arr = np.array([1, 34, 54, 32, 92, 12, 44, 87, 86, 23])
print(arr)

print("basic slicing: ", arr[2:7])
print("with step slicing: ", arr[1:8:2])
print("negative indexing: ", arr[-3])


# 2-D array
arr_2d = np.array([[1, 2, 4],
                   [3, 4, 5],
                   [6, 7, 8]])
print("specific element: ",arr_2d[1, 2])
print("specific element: ",arr_2d[2][1])

print("entire row: ", arr_2d[1])

print("entire column: ", arr_2d[:, 0])

[ 1 34 54 32 92 12 44 87 86 23]
basic slicing:  [54 32 92 12 44]
with step slicing:  [34 32 12 87]
negative indexing:  87
specific element:  5
specific element:  7
entire row:  [3 4 5]
entire column:  [1 3 6]


* Sorting

In [28]:
# 1-d array
unsorted = np.array([45, 65, 12, 54, 97, 14, 78, 15, 49])
print("sorted array is: ",np.sort(unsorted))


# 2-d array
arr_2d_unsorted = np.array([[15, 28, 46], [30, 44, 51], [69, 70, 8]])
# sorted by column with axis=0
print("unsorted array by column is: ",np.sort(arr_2d_unsorted, axis=0))
# sorted by rows with axis=1
print("unsorted array by row is: ",np.sort(arr_2d_unsorted, axis=1))

sorted array is:  [12 14 15 45 49 54 65 78 97]
unsorted array by column is:  [[15 28  8]
 [30 44 46]
 [69 70 51]]
unsorted array by row is:  [[15 28 46]
 [30 44 51]
 [ 8 69 70]]


* Filtering the numpy arrays
* filter with mask
    * A masked array is the combination of a standard numpy.ndarray and a mask.
    * A mask is either nomask, indicating that no value of the associated array is invalid, or an array of booleans that determines for each element of the associated array whether the value is valid or not.
    * When an element of the mask is False, the corresponding element of the associated array is valid and is said to be unmasked.
    * When an element of the mask is True, the corresponding element of the associated array is said to be masked (invalid).

In [29]:
numbers = np.array([1, 34, 54, 32, 92, 12, 44, 87, 86, 23])
even_number = numbers[numbers % 2 == 0]
print(even_number)



#filter with mask -> mask ek expression hai jo kisi number ko evaluate karta hai
mask = numbers > 5
print(mask)
print(numbers[mask])

[34 54 32 92 12 44 86]
[False  True  True  True  True  True  True  True  True  True]
[34 54 32 92 12 44 87 86 23]


* Fancy indexing vs np.where()

In [30]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where: ", numbers[where_result])

[ 1 54 92]
NP where:  [34 54 32 92 12 44 87 86 23]


* conditional array

In [31]:
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition_array = np.where(num > 5, num * 4, num)
print(condition_array)

# np.where(num > 5, num * 4, num) this statement is also same like as
# if(num > 5){
#     num * 4
# } else {
#     num
# }

[ 1  2  3  4  5 24 28 32 36 40]


### Array Manipulation

In [32]:
array = np.random.randint(10, 50, (4, 7))
print(array)
print(array.shape)

# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

# another method to find the transpose
trans2 = array.T
print(trans2)
print(trans2.shape)

[[36 11 27 47 16 10 30]
 [20 36 17 17 37 14 43]
 [40 44 18 44 37 49 12]
 [47 35 48 17 46 22 36]]
(4, 7)
[[36 20 40 47]
 [11 36 44 35]
 [27 17 18 48]
 [47 17 44 17]
 [16 37 37 46]
 [10 14 49 22]
 [30 43 12 36]]
(7, 4)
[[36 20 40 47]
 [11 36 44 35]
 [27 17 18 48]
 [47 17 44 17]
 [16 37 37 46]
 [10 14 49 22]
 [30 43 12 36]]
(7, 4)


In [33]:
a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.shape)

# reshaping the array
b = a.reshape(3, 2)
print(b)
print(b.shape)

[[4 1 4]
 [8 6 3]]
(2, 3)
[[4 1]
 [4 8]
 [6 3]]
(3, 2)


### Difference btw Scaler, Vector and Tensor

1. Scalar:
* A single numerical value.
* Represented as a 0-dimensional array in NumPy.
* Example: 2, 3.14, or -5.
2. Vector:
* An ordered collection of scalars (numbers).
* Represented as a 1-dimensional array in NumPy.
* Example: [1, 2, 3] or [4, 5, 6, 7].
3. Matrix:
* A 2-dimensional array of numbers.
* Represented as a 2-dimensional array in NumPy.
* Example: [[1, 2], [3, 4]].
4. Tensor:
* A generalization of matrices to n-dimensions (n > 2).
* Represented as an n-dimensional array in NumPy.
* Example: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] (a 3D tensor

In [34]:
# tensor
# ex-1
tensor1 = np.array([[[1, 2], [3, 4], [5, 6]],
                   [[7, 8], [9, 10], [11, 12]],
                   [[13, 14], [15, 16], [17, 18]]])
print(tensor1)
print(tensor1.shape)
print(tensor1.ndim)

# Imp Point----> The elements stored in the tensor must have the same no of elements, same no of rows and the same no of columns.

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
(3, 3, 2)
3


(3, 3, 2) means that
* 3 = no of arrays
* 3 = no of rows and
* 2 = no of cols

* Array compatibility

In [35]:
a1 = np.array([1, 2, 5])
a2 = np.array([7, 8, 9])
a3 = np.array([12, 13, 14])

print("compatibility shapes: ", a1.shape == a2.shape == a3.shape)

compatibility shapes:  True


* Adding extra row and column in array

In [36]:
# adding row
print("adding extra row")
original = np.array([[1, 2], [3, 4], [7, 8]])
new_row = np.array([[11, 12]])

# vstack ---> vertical stack
with_new_row = np.vstack((original, new_row))
print("with new row : ",with_new_row)



# adding column
print("adding extra column")
new_col = np.array([[70], [30], [100]])

# hstack ---> horizontal stack
with_new_col = np.hstack((original, new_col))
print("with new columns : ",with_new_col)



# adding element
element = np.array([[1, 2, 3, 3, 4, 5, 6, 7, 8]])
add_element = np.insert(element, 3, 45)
print("element: ", add_element)

adding extra row
with new row :  [[ 1  2]
 [ 3  4]
 [ 7  8]
 [11 12]]
adding extra column
with new columns :  [[  1   2  70]
 [  3   4  30]
 [  7   8 100]]
element:  [ 1  2  3 45  3  4  5  6  7  8]


* deletion operation

In [37]:
# delete the element
arrr = np.array([[1, 2, 3, 5, 3, 6, 7, 5]])
deleted = np.delete(arrr, 2)
print("array after deletion: ", deleted)



# delete the row -> numpy.delete(array_name, obj, axis=None)
obj = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
deleted_row = np.delete(obj, 0, 0)
print("array after deleted 0th row: ", deleted_row)



# delete the column -> numpy.delete(array_name, obj, axis=None)
deleted_col = np.delete(obj, 1, 1)
print("array after deleted 1st column: ", deleted_col)

array after deletion:  [1 2 5 3 6 7 5]
array after deleted 0th row:  [[ 5  6  7  8]
 [ 9 10 11 12]]
array after deleted 1st column:  [[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]
